-- =========================================================
--  ONLINE STORE DATABASE
--  Script 3 of 3 : Demonstration Queries
--  Run 01_schema.sql and 02_sample_data.sql first.
--
--  Each query below is documented with its purpose and the
--  SQL features it demonstrates, as required by the
--  assignment (Part 3: "at least five SQL queries that
--  demonstrate key features"). Queries 1-5 satisfy that
--  minimum; 6-7 are bonus queries.
-- =========================================================


-- ---------------------------------------------------------
-- Query 1 : Full detail of a customer's orders
-- Demonstrates : multi-table JOIN, ORDER BY
-- Goal         : retrieve every product bought by
--                "Ana Kovac", with order date and line total.
-- ---------------------------------------------------------
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    o.order_id,
    o.order_date,
    p.name                        AS product_name,
    oi.quantity,
    oi.unit_price,
    (oi.quantity * oi.unit_price) AS line_total
FROM customers c
JOIN orders o       ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id   = o.order_id
JOIN products p     ON p.product_id  = oi.product_id
WHERE c.email = 'ana.kovac@example.com'
ORDER BY o.order_date, p.name;


-- ---------------------------------------------------------
-- Query 2 : Search for products by category and price range
-- Demonstrates : JOIN, WHERE with range condition, sorting
-- Goal         : find all Electronics products priced
--                60 EUR or less.
-- ---------------------------------------------------------
SELECT
    p.name,
    p.price,
    p.stock_quantity,
    cat.name AS category
FROM products p
JOIN categories cat ON cat.category_id = p.category_id
WHERE cat.name = 'Electronics'
  AND p.price <= 60.00
ORDER BY p.price ASC;


-- ---------------------------------------------------------
-- Query 3 : Revenue generated by each product category
-- Demonstrates : JOIN across 4 tables, GROUP BY, SUM, ROUND
-- Goal         : help the store see which category earns
--                the most revenue.
-- ---------------------------------------------------------
SELECT
    cat.name AS category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM order_items oi
JOIN products p     ON p.product_id    = oi.product_id
JOIN categories cat ON cat.category_id = p.category_id
GROUP BY cat.name
ORDER BY total_revenue DESC;


-- ---------------------------------------------------------
-- Query 4 : Customers who have never placed an order
-- Demonstrates : LEFT JOIN combined with IS NULL
--                (an alternative to NOT EXISTS / NOT IN)
-- Goal         : identify inactive customers, e.g. for a
--                marketing email campaign.
-- ---------------------------------------------------------
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.customer_id
WHERE o.order_id IS NULL;


-- ---------------------------------------------------------
-- Query 5 : Top-selling products by quantity
-- Demonstrates : GROUP BY, SUM, ORDER BY + LIMIT (ranking)
-- Goal         : find the 3 best-selling products overall.
-- ---------------------------------------------------------
SELECT
    p.name,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.name
ORDER BY units_sold DESC
LIMIT 3;


-- ---------------------------------------------------------
-- Query 6 (bonus) : Orders with an unpaid or pending payment
-- Demonstrates : JOIN, WHERE with IN
-- Goal         : support the store's accounting /
--                follow-up process.
-- ---------------------------------------------------------
SELECT
    o.order_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    o.status   AS order_status,
    pay.status AS payment_status,
    pay.amount
FROM orders o
JOIN customers c  ON c.customer_id = o.customer_id
JOIN payments pay ON pay.order_id  = o.order_id
WHERE pay.status IN ('pending', 'failed')
ORDER BY o.order_date;


-- ---------------------------------------------------------
-- Query 7 (bonus) : Average order value per customer
-- Demonstrates : GROUP BY with HAVING, AVG, ROUND,
--                correlated scalar subquery
-- Goal         : find customers whose average order value
--                is above the store-wide average.
-- ---------------------------------------------------------
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    ROUND(AVG(o.total_amount), 2)       AS avg_order_value
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING AVG(o.total_amount) > (
    SELECT AVG(total_amount) FROM orders
)
ORDER BY avg_order_value DESC;
